// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Empower.DataAccess.Entities.Empower;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace Empower.DataAccess.ApplicationContext.Empower.Configurations
{
    public partial class DataTagConfiguration : IEntityTypeConfiguration<DataTag>
    {
        public void Configure(EntityTypeBuilder<DataTag> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_DataTagConfiguration");

            entity.Property(e => e.BioMarkerAndValueGuids).HasMaxLength(500);
            entity.Property(e => e.CancerTypeName).HasMaxLength(200);
            entity.Property(e => e.CreatedBy).HasMaxLength(100);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.DrugGPIs).HasMaxLength(200);
            entity.Property(e => e.DrugNames).HasMaxLength(500);
            entity.Property(e => e.LineOfTreatmentGuids).HasMaxLength(200);
            entity.Property(e => e.ModifiedBy).HasMaxLength(100);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.OverAllSurvivalRates).HasMaxLength(500);
            entity.Property(e => e.PathlogyGuids).HasMaxLength(500);
            entity.Property(e => e.PatientGender)
            .HasMaxLength(10)
            .IsFixedLength();
            entity.Property(e => e.PayerLOBGuid).HasMaxLength(500);
            entity.Property(e => e.PayerLOBName).HasMaxLength(500);
            entity.Property(e => e.RegimenGuids).HasMaxLength(500);
            entity.Property(e => e.StageGuids).HasMaxLength(500);
            entity.Property(e => e.TagName).HasMaxLength(200);
            entity.Property(e => e.TreatmentGoalGuids).HasMaxLength(200);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<DataTag> entity);
    }
}
