// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Empower.DataAccess.Entities.Empower;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace Empower.DataAccess.ApplicationContext.Empower.Configurations
{
    public partial class EmpowerFileConfiguration : IEntityTypeConfiguration<EmpowerFile>
    {
        public void Configure(EntityTypeBuilder<EmpowerFile> entity)
        {
            entity.HasKey(e => e.Id).HasName("PK_File");

            entity.Property(e => e.Comments)
            .HasMaxLength(1000)
            .IsUnicode(false);
            entity.Property(e => e.CreatedBy)
            .HasMaxLength(256)
            .IsUnicode(false);
            entity.Property(e => e.CreatedDate).HasColumnType("datetime");
            entity.Property(e => e.Extension)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.FileName).HasMaxLength(1024);
            entity.Property(e => e.LogicalLocation).HasMaxLength(1024);
            entity.Property(e => e.MimeType)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.ModifiedBy)
            .HasMaxLength(256)
            .IsUnicode(false);
            entity.Property(e => e.ModifiedDate).HasColumnType("datetime");
            entity.Property(e => e.Version)
            .HasMaxLength(50)
            .IsUnicode(false);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<EmpowerFile> entity);
    }
}
