// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Empower.DataAccess.Entities.Empower;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace Empower.DataAccess.ApplicationContext.Empower.Configurations
{
    public partial class RegisteredPatientClinicalDatumConfiguration : IEntityTypeConfiguration<RegisteredPatientClinicalDatum>
    {
        public void Configure(EntityTypeBuilder<RegisteredPatientClinicalDatum> entity)
        {
            entity.Property(e => e.BusinessEntityName).HasMaxLength(100);
            entity.Property(e => e.CancerType).HasMaxLength(100);
            entity.Property(e => e.LOT).HasMaxLength(50);
            entity.Property(e => e.Pathology).HasMaxLength(50);
            entity.Property(e => e.ProviderName).HasMaxLength(100);
            entity.Property(e => e.Stage).HasMaxLength(50);
            entity.Property(e => e.TreatmentEndDate).HasColumnType("datetime");
            entity.Property(e => e.TreatmentStartDate).HasColumnType("datetime");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<RegisteredPatientClinicalDatum> entity);
    }
}
