// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Empower.DataAccess.Entities.Empower;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace Empower.DataAccess.ApplicationContext.Empower.Configurations
{
    public partial class TreatmentQuestionToFileConnectorConfiguration : IEntityTypeConfiguration<TreatmentQuestionToFileConnector>
    {
        public void Configure(EntityTypeBuilder<TreatmentQuestionToFileConnector> entity)
        {
            entity.HasKey(e => new { e.TreamentQuestionId, e.FileId });

            entity.ToTable("TreatmentQuestionToFileConnector");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<TreatmentQuestionToFileConnector> entity);
    }
}
