// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Empower.DataAccess.Entities.Eviti;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace Empower.DataAccess.ApplicationContext.Eviti.Configurations
{
    public partial class ContactPayerConfiguration : IEntityTypeConfiguration<ContactPayer>
    {
        public void Configure(EntityTypeBuilder<ContactPayer> entity)
        {
            entity.HasKey(e => e.PayerGuid);

            entity.ToTable("ContactPayer");

            entity.HasIndex(e => e.EvitiDisplayName, "ix_ContactPayer_included");

            entity.Property(e => e.PayerGuid).ValueGeneratedNever();
            entity.Property(e => e.EligibilityVerifier)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.EvitiDisplayName)
            .HasMaxLength(100)
            .IsUnicode(false);
            entity.Property(e => e.IncludeEndDateCushion)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.InsuranceIDHintText).HasMaxLength(500);
            entity.Property(e => e.IsActive)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.IsInPublicList)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.IsPayerEmailOn)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.Name)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.NetworkMessage).HasMaxLength(1000);
            entity.Property(e => e.NotInNetworkMessage).HasMaxLength(1000);
            entity.Property(e => e.ParameterDictionary).IsUnicode(false);
            entity.Property(e => e.PayerID)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.RegistrationPin)
            .HasMaxLength(50)
            .IsUnicode(false);
            entity.Property(e => e.ShowInsuranceIDHint).HasDefaultValueSql("((0))");
            entity.Property(e => e.ShowPlanCompliantColumn)
            .IsRequired()
            .HasDefaultValueSql("((1))");
            entity.Property(e => e.TreatmentEndDate).HasDefaultValueSql("((365))");
            entity.Property(e => e.TurnaroundClockType).HasDefaultValueSql("((1))");
            entity.Property(e => e.TurnaroundStandardHours).HasDefaultValueSql("((360))");
            entity.Property(e => e.TurnaroundUrgentHours).HasDefaultValueSql("((72))");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ContactPayer> entity);
    }
}
